application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: LoginPage.application

- url: /manage
  script: ManagePage.application

- url: /create
  script: CreatePage.application

- url: /view
  script: ViewPage.application

- url: /viewall
  script: ViewAllPage.application

- url: /search
  script: SearchPage.application

- url: /trending
  script: TrendingPage.application

- url: /error
  script: ErrorPage.application

- url: /.*
  script: LoginPage.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest